const weatherDescKo = [
    { 201: { description: '비, 천둥구름', img: '/weather/thunder_cloud.jpg' } },
    { 200: { description: '비, 천둥구름',  img: '/weather/thunder_cloud.jpg' } },
    { 202: { description: '폭우, 천둥구름',  img: '/weather/thunder_cloud.jpg' } },
    { 210: { description: '천둥구름', img: '/weather/thunder_cloud.jpg' } },
    { 211: { description: '천둥구름',  img: '/weather/thunder_cloud.jpg' } },
    { 212: { description: '강한 천둥구름', img: '/weather/thunder_cloud.jpg' } },
    { 221: { description: '천둥구름',  img: '/weather/thunder_cloud.jpg' } },
    { 230: { description: '천둥구름',  img: '/weather/thunder_cloud.jpg' } },
    { 231: { description: '천둥구름',  img: '/weather/thunder_cloud.jpg' } },
    { 232: { description: '안개비, 천둥구름', img: '/weather/thunder_cloud.jpg' } },
    { 300: { description: '안개비',  img: '/weather/main.jpg' } },
    { 301: { description: '안개비',  img: '/weather/main.jpg' } },
    { 302: { description: '안개비',  img: '/weather/main.jpg' } },
    { 310: { description: '약한 비', img: '/weather/main.jpg' } },
    { 311: { description: '약한 비', img: '/weather/main.jpg' } },
    { 312: { description: '약한 비', img: '/weather/main.jpg' } },
    { 313: { description: '소나기',  img: '/weather/main.jpg' } },
    { 314: { description: '소나기', img: '/weather/main.jpg' } },
    { 321: { description: '소나기', img: '/weather/main.jpg' } },
    { 500: { description: '약한 비', img: '/weather/main.jpg' } },
    { 501: { description: '중간 비', img: '/weather/main.jpg' } },
    { 502: { description: '폭우',  img: '/weather/main.jpg' } },
    { 503: { description: '폭우',  img: '/weather/main.jpg' } },
    { 504: { description: '폭우' ,  img: '/weather/main.jpg' } },
    { 511: { description: '우박' ,  img: '/weather/main.jpg' } },
    { 520: { description: '소나기',  img: '/weather/main.jpg' } },
    { 521: { description: '소나기' ,  img: '/weather/main.jpg' } },
    { 522: { description: '소나기' ,  img: '/weather/main.jpg' } },
    { 531: { description: '소나기' ,  img: '/weather/main.jpg' } },
    { 600: { description: '눈' , img: '/weather/main.jpg' } },
    { 601: { description: '눈' ,  img: '/weather/main.jpg' } },
    { 602: { description: '폭설' ,  img: '/weather/main.jpg' } },
    { 611: { description: '진눈깨비',  img: '/weather/main.jpg' } },
    { 612: { description: '소나기, 진눈깨비', img: '/weather/main.jpg' } },
    { 615: { description: '약한 비와 눈', img: '/weather/main.jpg' } },
    { 616: { description: '비와 눈',  img: '/weather/main.jpg' } },
    { 620: { description: '약한 소나기 눈',  img: '/weather/main.jpg' } },
    { 621: { description: '소나기 눈' , img: '/weather/main.jpg' } },
    { 622: { description: '강한 소나기 눈' ,  img: '/weather/main.jpg' } },
    { 701: { description: '안개',  img: '/weather/main.jpg' } },
    { 711: { description: '안개',  img: '/weather/main.jpg' } },
    { 721: { description: '안개',  img: '/weather/main.jpg' } },
    { 731: { description: '모래 먼지' , img: '/weather/main.jpg' } },
    { 741: { description: '안개',  img: '/weather/main.jpg' } },
    { 751: { description: '모래', img: '/weather/main.jpg' } },
    { 761: { description: '먼지' , img: '/weather/main.jpg' } },
    { 762: { description: '화산재' , img: '/weather/main.jpg' } },
    { 771: { description: '돌풍' ,  img: '/weather/main.jpg' } },
    { 781: { description: '토네이도' ,  img: '/weather/main.jpg' } },
    { 800: { description: '맑음' ,  img: '/weather/main.jpg' } },
    { 801: { description: '구름 조금' , img: '/weather/main.jpg' } },
    { 802: { description: '구름 조금' , img: '/weather/main.jpg' } },
    { 803: { description: '맑음',  img: '/weather/main.jpg' } },
    { 804: { description: '흐림' ,  img: '/weather/main.jpg' } },
    { 900: { description: '토네이도', img: '/weather/main.jpg' } },
    { 901: { description: '태풍' ,  img: '/weather/main.jpg' } },
    { 902: { description: '허리케인' ,  img: '/weather/main.jpg' } },
    { 903: { description: '한랭' ,  img: '/weather/main.jpg' } },
    { 904: { description: '고온' ,  img: '/weather/main.jpg' } },
    { 905: { description: '바람 조금' ,  img: '/weather/main.jpg' } },
    { 906: { description: '우박' ,  img: '/weather/main.jpg' } },
    { 951: { description: '바람 없음' ,  img: '/weather/main.jpg' } },
    { 952: { description: '약한 바람' ,  img: '/weather/main.jpg' } },
    { 953: { description: '약한 바람', img: '/weather/main.jpg' } },
    { 954: { description: '중간 바람', img: '/weather/main.jpg' } },
    { 955: { description: '신선한 바람',  img: '/weather/main.jpg' } },
    { 956: { description: '센 바람',  img: '/weather/main.jpg' } },
    { 957: { description: '센 바람' ,  img: '/weather/main.jpg' } },
    { 958: { description: '돌풍',  img: '/weather/main.jpg' } },
    { 959: { description: '돌풍' ,  img: '/weather/main.jpg' } },
    { 960: { description: '폭풍' , img: '/weather/main.jpg' } },
    { 961: { description: '강한 폭풍' , img: '/weather/main.jpg' } },
    { 962: { description: '허리케인' ,  img: '/weather/main.jpg' } },
  ]
  
export default weatherDescKo;